version: 2.1

executors:
  builder:
    machine:
      image: ubuntu-1604:202007-01 # # recommended linux image - includes Ubuntu 16.04, Docker v19.03.12, Docker Compose v1.26.1
      #image: ubuntu-1604:202004-01 # Ubuntu 16.04, Docker v19.03.8, Docker Compose v1.25.5
      #image: ubuntu-1604:201903-01 # Ubuntu 16.04, Docker v18.09.3, Docker Compose v1.23.1

jobs:

  unittests:
    executor: builder
    steps:
      - checkout
      - run:
          name: Install python 3.8
          command: |
            sudo apt-get update
            sudo apt-get -y install software-properties-common
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt-get update
            sudo apt-get -y install python3.8
      - run:
          name: Run unit tests
          command: make test-unittest

  truffletests:
    executor: builder
    steps:
      - checkout
      - run:
          name: Run truffle erc-to-erc tests
          command: make test-truffle-erc-to-erc
      - run:
          name: Run truffle native-to-erc tests
          command: make test-truffle-native-to-erc

  e2etests:
    executor: builder
    steps:
      - checkout
      - run:
          name: Run e2e erc-to-erc tests
          command: make test-e2e-erc-to-erc
      - run:
          name: Run e2e native-to-erc tests
          command: make test-e2e-native-to-erc

  contracttests:
    executor: builder
    steps:
      - checkout
      - run:
          name: Run contract tests
          command: make test-contracts

workflows:

  github-pull-request:
    jobs:
      - unittests
      - truffletests
      - contracttests
      - e2etests
        # filters:
        #    branches:
        #      only:
        #        - master
