version: '2'
services:
  test-e2e:
    build: .
    image: e2e
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ../data:/stuff/data
      - ../abis:/stuff/abis
      - ./test:/stuff/test
  e2e-erc-to-erc:
    extends: test-e2e
    command: npx mocha test/ercToErc.js
  e2e-native-to-erc:
    extends: test-e2e
    command: npx mocha test/nativeToErc.js
  e2e-erc-to-native:
    extends: test-e2e
    command: npx mocha test/ercToNative.js